export const mapMFFundToFundCardProps = (fund: any) => {
  return {
    schemeName: fund.fund_name,
    benchmarkName: fund.benchmark_index_name,
    amcName: fund.amc_id?.name ?? "",
    category: fund.category_id?.name ?? "",
    nav: fund.nav_Current,
    navCurrent: fund.nav_Current,
    navDate: fund.nav_date,
    navChange: fund.nav_change,
    navChangePct: fund.nav_change_percentage,
    exitLoad: fund.exit_load,
    rating: fund.rating,
    ratingValue: fund.rating_value,
    isin: fund.isin,
    schemeCode: fund.scheme_code,
    aum: fund.aum_cr,
    fundManager: fund.fund_manager,
    expenseRatio: fund.expense_ratio,
    planType: fund.plan_type,
    optionType: fund.option_type,
    riskometerLabel: fund.riskometer_label,
    launchDate: fund.launch_date,
    returnsSinceInception: fund.returns?.since_inception,
    returnsAnnualYtd: fund.returns?.annual?.ytd,
    benchmarkReturnsAnnual: fund.benchmark_returns_annual,
    benchmarkReturnsTrailing: fund.benchmark_returns_trailing,
    benchmarkInceptionReturn: fund.benchmark_inception_return,
    minInvestment: fund.min_investment,
    minSip: fund.min_sip_investment,
    minLumpsum: fund.min_lumpsum_investment,
    sipAllowed: fund.sip_allowed,
    lumpsumAllowed: fund.lumpsum_allowed,
    fundObjective: fund.fund_objective,
    schemeObjective: fund.fund_objective,

    // Risk Metrics
    stdDev: fund.risk_metrics?.std_dev_3y,
    stdDev5y: fund.risk_metrics?.std_dev_5y,
    sharpe: fund.risk_metrics?.sharpe_3y,
    sharpe5y: fund.risk_metrics?.sharpe_5y,
    sortino: fund.risk_metrics?.sortino,
    beta: fund.risk_metrics?.beta_1y,
    beta3y: fund.risk_metrics?.beta_3y,
    beta5y: fund.risk_metrics?.beta_5y,
    alpha: fund.risk_metrics?.alpha_1y,
    alpha3y: fund.risk_metrics?.alpha_3y,
    alpha5y: fund.risk_metrics?.alpha_5y,
    maxDrawdown5y: fund.risk_metrics?.max_drawdown_5y,
    maxDrawdown10y: fund.risk_metrics?.max_drawdown_10y,
    upmarketCapture: fund.upmarket_capture_ratio,
    downmarketCapture: fund.downmarket_capture_ratio,
    yieldToMaturity: fund.risk_metrics?.yield_to_maturity,
    averageMaturity: fund.risk_metrics?.average_maturity,
    schemeTurnover: fund.risk_metrics?.turnover_ratio,

    // Asset/Cap allocation
    largeCapPct: fund.large_cap_pct,
    midCapPct: fund.mid_cap_pct,
    smallCapPct: fund.small_cap_pct,
    domesticEquityPct: fund.domestic_equity_pct,
    internationalEquityPct: fund.international_equity_pct,
    debtPct: fund.debt_pct,
    cashPct: fund.cash_pct,
    otherPct: fund.other_pct,
    goldPct: fund.gold_pct,

    // Returns
    returns: fund.returns,

    // API bridged arrays
    performanceList: fund.mf_api_scheme_id?.scheme_performance_list || [],
    riskStatsList: fund.mf_api_scheme_id?.risk_statistics_list || [],
    peerList: fund.mf_api_scheme_id?.scheme_peer_comparision_list || [],
    topHoldings: fund.top_holdings?.holdings || [],
  };
};
